name: ppa
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*
  - pip
  - pandas
  - numpy
  - pandas-datareader
  - jupyterlab
  - nbclassic>=0.3.*
  - requests-cache
  - pip:
    - alpha-vantage==2.3.*
    - pyxirr==0.6.*
    - streamlit==1.0.*